
from __future__ import annotations
from pathlib import Path
from PIL import Image, ImageOps, ImageEnhance, ImageFilter
import json, zipfile, datetime

def perspective_dewarp(im, quad):
    # quad order: top-left, top-right, bottom-right, bottom-left
    src=im.convert("RGBA")
    w,h=src.size
    pts=[tuple(map(float,p)) for p in quad]
    tl,tr,br,bl=pts
    def dist(a,b): return ((a[0]-b[0])**2+(a[1]-b[1])**2)**0.5
    ow=max(1,int(round((dist(tl,tr)+dist(bl,br))/2)))
    oh=max(1,int(round((dist(tl,bl)+dist(tr,br))/2)))
    # Pillow's transform expects coefficients mapping output -> input.
    x0,y0=tl; x1,y1=tr; x2,y2=br; x3,y3=bl
    # solve homography numerically via 8x8 Gaussian elimination
    A=[]; B=[]
    dst=[(0,0),(ow-1,0),(ow-1,oh-1),(0,oh-1)]
    for (x,y),(u,v) in zip(pts,dst):
        A += [[x,y,1,0,0,0,-u*x,-u*y],
              [0,0,0,x,y,1,-v*x,-v*y]]
        B += [u,v]
    M=[A[i][:]+[B[i]] for i in range(8)]
    for c in range(8):
        piv=max(range(c,8),key=lambda r:abs(M[r][c]))
        M[c],M[piv]=M[piv],M[c]
        if abs(M[c][c])<1e-12: return src
        q=M[c][c]
        for j in range(c,9): M[c][j]/=q
        for r in range(8):
            if r==c: continue
            q=M[r][c]
            for j in range(c,9): M[r][j]-=q*M[c][j]
    H=[M[i][8] for i in range(8)]
    # inverse mapping is obtained by solving destination coordinates through the forward H.
    # Pillow coefficients can be generated by inverting the 3x3 homography.
    a,b,c,d,e,f,g,h=H
    det=a*(e-h*f)-b*(d-h*c)+c*(d*h-e*g)
    if abs(det)<1e-12: return src
    ia=(e-h*f)/det; ib=(c*h-b)/det; ic=(b*f-c*e)/det
    id=(f*g-d)/det; ie=(a*d-c*g)/det; iff=(b*g-a*f)/det
    ig=(d*h-e*g)/det; ih=(b*g-a*h)/det; ii=(a*e-b*d)/det
    coeff=(ia,ib,ic,id,ie,iff,ig,ih)
    return src.transform((ow,oh),Image.Transform.PERSPECTIVE,coeff,Image.Resampling.LANCZOS)

class History:
    def __init__(self, limit=12):
        self.limit=limit; self.items=[]; self.index=-1
    def push(self, im):
        self.items=self.items[:self.index+1]
        self.items.append(im.copy())
        if len(self.items)>self.limit: self.items.pop(0)
        self.index=len(self.items)-1
    def undo(self):
        if self.index>0: self.index-=1; return self.items[self.index].copy()
    def redo(self):
        if self.index+1<len(self.items): self.index+=1; return self.items[self.index].copy()

def batch_process(paths, operation, output_dir):
    out=Path(output_dir); out.mkdir(parents=True,exist_ok=True); results=[]
    for p in paths:
        try:
            im=Image.open(p).convert("RGBA"); im=operation(im)
            target=out/(Path(p).stem+"_processed.png"); im.save(target,"PNG")
            results.append({"source":str(p),"output":str(target),"ok":True})
        except Exception as e:
            results.append({"source":str(p),"ok":False,"error":str(e)})
    return results
